[package]
name = "vox-gltf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-mesh = "0.2.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
dot_vox = "5.1.1"
gltf = "1.3.0"
gltf-json = "1.3.0"
slab = "0.4.9"
